[package]
name = "shh"
version = "2023.12.16"
authors = ["Maxime Desbrus <maxime.desbrus@synacktiv.com>"]
description = "Automatic systemd service hardening guided by strace profiling"
readme = "README.md"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = { version = "1.0.72", default-features = false, features = ["std", "backtrace"] }
bincode = { version = "1.3.3", default-features = false }
clap = { version = "4.3.17", default-features = false, features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive"] }
itertools = { version = "0.11.0", default-features = false, features = ["use_std"] }
lazy_static = { version = "1.4.0", default-features = false }
log = { version = "0.4.19", default-features = false, features = ["max_level_trace", "release_max_level_info"] }
nix = { version = "0.26.2", default-features = false, features = ["fs"] }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
regex = { version = "1.9.1", default-features = false, features = ["std", "perf"] }
serde = { version = "1.0.193", default-features = false, features = ["std", "derive"] }
signal-hook = { version = "0.3.17", default-features = false, features = ["iterator"] }
simple_logger = { version = "4.2.0", default-features = false, features = ["colors", "stderr"] }
strum = { version = "0.25.0", default-features = false, features = ["std", "derive"] }
tempfile = { version = "3.7.0", default-features = false }

[dev-dependencies]
assert_cmd = { version = "2.0.12", default-features = false, features = ["color", "color-auto"] }
fastrand = { version = "2.0.0", default-features = false, features = ["std"] }
nix = { version = "0.26.2", default-features = false, features = ["user"] }
predicates = { version = "3.0.3", default-features = false, features = ["color"] }
pretty_assertions = { version = "1.4.0", default-features = false, features = ["std"] }

[features]
# for benchmarks only
nightly = []
# for tests only
as-root = []

[package.metadata.deb]
name = "shh"
depends = "$auto, strace"
